enum TICKETS {
  FETCH = 'TICKETS/FETCH',
  FETCH_START = 'TICKETS/FETCH_START',
  FETCH_END = 'TICKETS/FETCH_END',
  ADD = 'TICKETS/ADD',
}

enum FILTER {
  UPDATE = 'FILTER/UPDATE',
}

export { TICKETS, FILTER }
