enum TICKETS {
  FETCH = 'TICKETS/FETCH',
  FETCH_START = 'TICKETS/FETCH_START',
  FETCH_END = 'TICKETS/FETCH_END',
  ADD = 'TICKETS/ADD',
}

enum FILTER {
  TOGGLE = 'FILTER/TOGGLE',
  UPDATE = 'FILTER/UPDATE',
}

enum SORT {
  SWITCH = 'SORT/SWITCH',
  UPDATE = 'SORT/UPDATE',
}

enum SEARCH_ID {
  SET = 'SEARCH_ID/SET',
}

export { TICKETS, FILTER, SORT, SEARCH_ID }
